version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: dummy_pg_db
    restart: always
    environment:
      POSTGRES_USER: dummy_user
      POSTGRES_PASSWORD: dummy_password
      POSTGRES_DB: dummy_payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
